name: API Nexttalents - Push-to-EC2 CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Chechout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm dependencies
        run: npm install

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t back-nexttalents:latest .
      - name: Tag Docker image
        run: docker tag back-nexttalents:latest ${{ secrets.DOCKER_USERNAME }}/back-nexttalents:latest
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/back-nexttalents:latest

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.REMOTE_HOST}}
          username: "ec2-user"
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            docker stop back-nexttalents || true
            docker rm back-nexttalents || true
            docker pull ${{ secrets.DOCKER_USERNAME }}/back-nexttalents
            docker run --restart=always -d --name back-nexttalents -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/back-nexttalents
            docker cp nextTalents/back/.variable.env back-nexttalents:/home/node/app
            docker cp nextTalents/back/.env back-nexttalents:/home/node/app

